# docker-compose file for minimal deployment

version: '2'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "!postgres@-"
    volumes:
      - pgdata:/var/lib/postgresql/data/
    ports:
      - "54321:5432"
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # command: bash -c "nginx & /usr/local/bin/gunicorn config.wsgi:application -w 2 -b :8001 --log-level=info --log-file - --access-logfile -"
    command: /app/entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8580:8000"
    links:
      - postgres

volumes:
  pgdata:
